# Generated by Django 5.2.1 on 2025-06-16 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Une petite biographie.')),
                ('profile_picture', models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/')),
                ('travel_style', models.CharField(blank=True, choices=[('ADVENTURE', 'Aventure & Plein Air'), ('RELAXATION', 'Détente & Plage'), ('CULTURE', 'Culture & Histoire'), ('BUDGET', 'Budget & Backpacking'), ('LUXURY', 'Luxe & Gastronomie'), ('FAMILY', 'En Famille')], help_text='Quel est votre style de voyage ?', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mon Voyage Planifié', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_cities_input_str', models.TextField(blank=True, null=True)),
                ('total_budget_str', models.CharField(blank=True, max_length=50, null=True)),
                ('num_days_str', models.CharField(blank=True, max_length=10, null=True)),
                ('num_persons', models.PositiveIntegerField(default=1, help_text='Nombre de personnes pour ce voyage.')),
                ('min_hotel_rating_str', models.CharField(blank=True, max_length=10, null=True)),
                ('activity_preferences_list_str', models.TextField(blank=True, null=True)),
                ('ordered_cities_json', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('city_name', models.CharField(blank=True, max_length=100, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='planner.trip')),
            ],
            options={
                'ordering': ['trip', 'day_number'],
                'unique_together': {('trip', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='DailyActivityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_in_day', models.PositiveIntegerField()),
                ('item_type', models.CharField(choices=[('hotel', 'Hôtel'), ('activity', 'Activité')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rating_general', models.FloatField(blank=True, null=True)),
                ('budget_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activity_type_name', models.CharField(blank=True, max_length=100, null=True)),
                ('duree_estimee', models.CharField(blank=True, max_length=50, null=True)),
                ('astar_segment_to_next_json', models.JSONField(blank=True, null=True)),
                ('trip_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_items', to='planner.tripday')),
            ],
            options={
                'ordering': ['trip_day', 'order_in_day'],
            },
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Ex: 'Une semaine magique à Marrakech'", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Racontez votre histoire, vos impressions...')),
                ('cover_image', models.ImageField(blank=True, help_text="L'image principale de votre voyage.", null=True, upload_to='voyage_covers/')),
                ('is_public', models.BooleanField(default=True, help_text='Rendre ce voyage visible aux autres utilisateurs ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to=settings.AUTH_USER_MODEL)),
                ('source_trip', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_voyage', to='planner.trip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoyageMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(upload_to='voyage_media/')),
                ('caption', models.CharField(blank=True, help_text='Légende pour cette image/audio.', max_length=255)),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VOCAL', 'Vocal')], default='IMAGE', max_length=5)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='planner.voyage')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_ratings', to=settings.AUTH_USER_MODEL)),
                ('daily_activity_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='planner.dailyactivityitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'daily_activity_item')},
            },
        ),
    ]
