# Generated by Django 5.2.1 on 2025-06-22 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityrating',
            options={},
        ),
        migrations.RemoveField(
            model_name='dailyactivityitem',
            name='activity_type_name',
        ),
        migrations.RemoveField(
            model_name='dailyactivityitem',
            name='astar_segment_to_next_json',
        ),
        migrations.RemoveField(
            model_name='dailyactivityitem',
            name='budget_estime',
        ),
        migrations.RemoveField(
            model_name='dailyactivityitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dailyactivityitem',
            name='duree_estimee',
        ),
        migrations.RemoveField(
            model_name='dailyactivityitem',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='dailyactivityitem',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='dailyactivityitem',
            name='price_per_night',
        ),
        migrations.RemoveField(
            model_name='dailyactivityitem',
            name='rating_general',
        ),
        migrations.RemoveField(
            model_name='voyage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='voyagemedia',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='voyagemedia',
            name='voyage',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyage_comments', to=settings.AUTH_USER_MODEL)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='planner.voyage')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, help_text="Ex: 'Découverte de la Médina'", max_length=200)),
                ('story', models.TextField(blank=True, help_text='Racontez cette journée...')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='planner.voyage')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('voyage', 'day_number')},
            },
        ),
        migrations.AddField(
            model_name='voyagemedia',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='planner.journalentry'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyage_likes', to=settings.AUTH_USER_MODEL)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='planner.voyage')),
            ],
            options={
                'unique_together': {('voyage', 'user')},
            },
        ),
    ]
