# Generated by Django 5.2.1 on 2025-06-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_activityrating_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dailyactivityitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tripday',
            options={},
        ),
        migrations.AlterModelOptions(
            name='voyage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='voyagemedia',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='activityrating',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='journalentry',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tripday',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='trip',
            name='activity_preferences_list_str',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='min_hotel_rating_str',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='ordered_cities_json',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='total_budget_str',
        ),
        migrations.RemoveField(
            model_name='voyage',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='voyagemedia',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='dailyactivityitem',
            name='activity_type_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voyagemedia',
            name='media_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('AUDIO', 'Audio')], default='IMAGE', max_length=5),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='story',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='travel_style',
            field=models.CharField(blank=True, choices=[('ADVENTURE', 'Aventure & Plein Air'), ('RELAXATION', 'Détente & Plage'), ('CULTURE', 'Culture & Histoire'), ('BUDGET', 'Budget & Backpacking'), ('LUXURY', 'Luxe & Gastronomie'), ('FAMILY', 'En Famille')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='num_persons',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='voyage_covers/'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='voyagemedia',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RemoveField(
            model_name='activityrating',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='activityrating',
            name='updated_at',
        ),
    ]
