# Generated by Django 5.2.1 on 2025-08-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0004_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
