# Generated by Django 5.2.1 on 2025-08-08 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0005_chatmessage_metadata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="metadata",
        ),
    ]
